function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"ASTRONOMY TRIVIA";
	window.questions = [		"WHAT IS THE DISTANCE OF EARTH TO THE MOON?", 
								"HOW MANY MOONS DOES JUPITER HAVE?",
								"WHICH PLANET IS THE ONLY ONE NOT NAMED AFTER ROMAN MYTHOLOGY GOD?", 
								"WHICH PLANET HAS THE HIGHEST DENSITY IN THE SOLAR SYSTEM?", 
								"WHAT IS THE HOTTEST PLANET IN THE SOLAR SYSTEM?",
								"WHAT YEAR WAS PLUTO DECLASSIFIED AS A PLANET?",
								"WHAT THREE PLANETS ARE THE ONLY ONES CREDITED WITH AN ASTRONOMER AND THE DATE THE PLANET WAS FOUND?",
								"WHEN THE SUN DIES, WHAT WILL IT TURN INTO AFTER THE INITIAL EVENT?",
								"WHEN WAS ASTROLOGY, THE BELIEF OF ALL HUMANS ARE CONNECTED TO CERTAIN STARS BASED ON THEIR BIRTHDAYS, WAS FIRST INVENTED?",
								"THE MILKY WAY IS DESTINED TO COLLIDE WITH ANOTHER GALAXY, WHAT IS THE NAME OF THE OTHER GALAXY?"];
	window.correctAnswer = [ 	"A", "D", "C", "E", "B", "B", "C", "E", "A", "D"]; 
	window.answerA = [ 			"238900 MILES", 
								"23 MOONS", 
								"VENUS", 
								"NEPTUNE", 
								"MERCURY" ,
								"2005" ,
								"MARS AND JUPITER AND SATURN" ,
								"COMET" ,
								"2400 YEARS AGO" ,
								"TRIANGULUM GALAXY"];
								
	window.answerB = [ 			"90000 MILES", 
								"69 MOONS", 
								"MOON", 
								"VENUS",
								"VENUS" ,
								"2006" ,
								"MERCURY AND VENUS AND MARS" ,
								"SUPER GIANT" ,
								"50 YEARS AGO" ,
								"BLACK EYE GALAXY" ];
								 
	window.answerC = [			"104032 MILES" ,
								"3 MOONS" ,
								"MARS" ,
								"MARS" ,
								"URANUS" ,
								"2010" ,
								"URANUS AND NEPTUNE AND PLUTO" ,
								"BLACK HOLE" ,
								"70000 YEARS AGO" ,
								"WHIRLPOOL GALAXY" ];
	
	
	window.answerD = [			"1000235 MILES" ,
								"79 MOONS" ,
								"EARTH" ,
								"JUPITER" ,
								"TITAN" ,
								"1996" ,
								"VENUS AND MARS AND EARTH" ,
								"RED GIANT" ,
								"1000 YEARS AGO" ,
								"ANDROMEDA GALAXY" ];
	
	window.answerE = [			"154437 MILES" ,
								"57 MOONS" ,
								"PLUTO" ,
								"EARTH" ,
								"SATURN" ,
								"1990" ,
								"JUPITER AND TITAN AND IO" ,
								"WHITE DWARF" ,
								"UNKNOWN" ,
								"SOMBRERO GALAXY" 
								];
	


	window.response = [ 		"IT TAKES ABOUT THREE EARTH DAYS TO REACH THE MOON", 
								"EACH MOON IS NAMED AFTER ONE ON THE ROMAN GODS JUPITERS LOVERS", 
								"THE WORD EARTH COMES FROM A ANGLO-SAXON WORD THAT MEANT GROUND",
								"THE DENSITY OF EARTH VARIES THROUGHOUT THE PLANET BUT THE AVERAGE DENSITY IS ABOUT 5.52 GRAMS PER CUBIC CENTIMETER", 
								"VENUS ATMOSPHERE TRAPS ALL THE HEAT ON THE PLANET MAKING ONLY THE SUN HOTTER THAN VENUS IN OUR SOLAR SYSTEM",
								"THE PLANET WAS DEEMED TOO SMALL TO BE CLASSIFIED AS A PLANET AND WAS SWITCHED TO DWARF PLANET STATUS",
								"ALL THE OTHERS PLANETS HAVE BEEN KNOWN TO EXIST FOR THOUSANDS OF YEARS MAKING IT DIFFICULT TO DETERMINE THE ASTRONOMER AND DATE THEY WERE DISCOVERED",
								"THE SUN WILL SUPER-SIZE IN 4-5 BILLION YEARS ENVELOPING MERCURY VENUS AND EARTH BEFORE SHRINKING TO ABOUT THE SIZE OF EARTH AS A WHITE DWARF",
								"THE BABYLONIANS STARTED THE MODERN DAY VERSION THAT WOULD EVENTUALLY SPREAD INTO ANCIENT GREECE",
								"THE TWO GALAXIES WILL COLLIDE IN ABOUT 4.5 BILLION YEARS, CREATING AN EVEN LARGER GALAXY" ];
							
}
						